baseURL = 'https://irsecdev-cpu.github.io/irporto/'
languageCode = 'en-us'
title = 'Portfolio | Project Overview'
theme = "congo"

[params]
  colorScheme = "ocean"
  appearance = "auto"
  mainSections = ["projects"]

[params.homepage]
  layout = "profile"
  showRecent = true
  recentLimit = 3
  showMoreLink = true

[params.profileMode]
  enabled = true
  title = "Hi! I'm IR"
  subtitle = "IT Portfolio | Dev & Analysis & Architecture"
  imageUrl = "img/avatar.png"
  imageSize = "150px"

[[params.profileMode.buttons]]
  name = "View Projects"
  url = "projects/"
  weight = 10

[[params.profileMode.buttons]]
  name = "CV / Resume"
  url = "cv.pdf"
  weight = 20

[[menu.main]]
  name = "Projects"
  pageRef = "projects"
  weight = 10

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/irsecdev-cpu"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/ramona-iovan"

[[params.socialIcons]]
  name = "email"
  url = "mailto:irsecdev@email.com"

[markup.goldmark.renderer]
  unsafe = true

[author]
  name = "IR"
